### ISSUE TITLE
About cargo-call-stack issue 'Failed to get bitcode from object file for LTO'

### ISSUE THREAD

**Issue by ysun** [jiayihu/brokerapi-rs#1]
Hi Jiayi,

I got you from cargo-call-stack issue https://github.com/japaric/cargo-call-stack/issues/32
I met exactly the same issue as yours. May I know what's your progress? Have you got the solution ?

Thanks
  --Yi Sun

**Comment by jiayihu** [comment]
Please don't open issue on unrelated repos
